name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js (se necessário)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies (se houver package.json)
      run: |
        if [ -f package.json ]; then
          npm install
          npm run build
        fi
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          git pull origin main
          sudo chown -R $USER:www-data .
          sudo chmod -R 755 .
          sudo systemctl reload apache2
